# Generated by Django 5.0.4 on 2025-01-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP пользователя')),
                ('comment', models.CharField(default='', max_length=1024, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'IP адреса',
            },
        ),
    ]
