# Generated by Django 5.0.4 on 2025-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_list_ip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetListIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('comment', models.CharField(default='', max_length=1024, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'IP адреса (для сброса/администрирования)',
            },
        ),
        migrations.AlterModelOptions(
            name='whitelistip',
            options={'verbose_name_plural': 'IP адреса (для работы)'},
        ),
        migrations.AlterField(
            model_name='whitelistip',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
    ]
