# Generated by Django 5.0.4 on 2025-01-17 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_list_ip', '0002_resetlistip_alter_whitelistip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelistip',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
