# Generated by Django 5.0.4 on 2025-01-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_list_ip', '0003_whitelistip_date_alter_whitelistip_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
