# Generated by Django 5.0.4 on 2025-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_list_ip', '0005_alter_whitelistip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistip',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Название'),
        ),
    ]
