# Generated by Django 5.0.4 on 2025-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsAddListIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'История добавления динамических IP адресов',
            },
        ),
    ]
