# Generated by Django 5.0.4 on 2025-08-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsLoginMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, verbose_name='Адрес электронной почты')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('result', models.CharField(max_length=256, verbose_name='Результат')),
                ('tech_info', models.TextField(verbose_name='Техническая информация')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'История входов на почту',
            },
        ),
    ]
