# Generated by Django 5.0.4 on 2025-08-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_statsloginmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsloginmail',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
    ]
