# Generated by Django 5.0.4 on 2025-08-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_statsloginmail_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsloginmail',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statsloginmail',
            name='email',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='statsloginmail',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='statsloginmail',
            name='result',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Результат'),
        ),
    ]
