# Generated by Django 5.0.4 on 2025-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_statsloginmail_date_alter_statsloginmail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsloginmail',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
