# Generated by Django 5.0.4 on 2025-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_statsloginmail_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsActiveMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес электронной почты')),
                ('date_start_active', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('date_end_active', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Активность работы на почте',
            },
        ),
        migrations.CreateModel(
            name='StatsBaseMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, verbose_name='Адрес электронной почты')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('count_input_email', models.IntegerField(blank=True, null=True, verbose_name='Количество входящих писем')),
                ('count_output_email', models.IntegerField(blank=True, null=True, verbose_name='Количество исходящих писем')),
                ('count_input_info_email', models.IntegerField(blank=True, null=True, verbose_name='Количество рекламных писем (входящих с info)')),
                ('count_output_bill_email', models.IntegerField(blank=True, null=True, verbose_name='Количество отправленных счетов')),
                ('count_output_kp_email', models.IntegerField(blank=True, null=True, verbose_name='Количество отправленных КП')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Общая статистика по почтам',
            },
        ),
        migrations.CreateModel(
            name='StatsIPMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес электронной почты')),
                ('date_start_active', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('date_end_active', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'IP которые работали на почтовом сервере',
            },
        ),
        migrations.CreateModel(
            name='StatsServerMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Имя пользователя')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления в статистику')),
            ],
            options={
                'verbose_name_plural': 'Перечень существующих на сервере почт',
            },
        ),
    ]
