# Generated by Django 5.0.4 on 2025-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_statsactivemail_statsbasemail_statsipmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsbasemail',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
