# Generated by Django 5.0.4 on 2025-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_statsbasemail_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsactivemail',
            options={'ordering': ['-date_start_active', 'email'], 'verbose_name_plural': 'Активность работы на почте'},
        ),
        migrations.AlterModelOptions(
            name='statsaddlistip',
            options={'ordering': ['-date'], 'verbose_name_plural': 'История добавления динамических IP адресов'},
        ),
        migrations.AlterModelOptions(
            name='statsbasemail',
            options={'ordering': ['-date', 'email'], 'verbose_name_plural': 'Общая статистика по почтам'},
        ),
        migrations.AlterModelOptions(
            name='statsipmail',
            options={'ordering': ['-date_start_active', 'ip_address'], 'verbose_name_plural': 'IP которые работали на почтовом сервере'},
        ),
        migrations.AlterModelOptions(
            name='statsservermail',
            options={'ordering': ['email'], 'verbose_name_plural': 'Перечень существующих на сервере почт'},
        ),
        migrations.AddField(
            model_name='statsbasemail',
            name='active_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='statsbasemail',
            name='count_input_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество входящих'),
        ),
        migrations.AlterField(
            model_name='statsbasemail',
            name='count_input_info_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество рекламных'),
        ),
        migrations.AlterField(
            model_name='statsbasemail',
            name='count_output_bill_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество счетов'),
        ),
        migrations.AlterField(
            model_name='statsbasemail',
            name='count_output_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество исходящих'),
        ),
        migrations.AlterField(
            model_name='statsbasemail',
            name='count_output_kp_email',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество КП'),
        ),
    ]
