# Generated by Django 5.0.4 on 2025-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_statsactivemail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsactivemail',
            name='date_end_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='statsactivemail',
            name='date_start_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='statsipmail',
            name='date_end_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='statsipmail',
            name='date_start_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='statsipmail',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='IP адрес'),
        ),
    ]
